import Nav from "@/components/Nav";

export default function TosPage() {
  return (
    <>
      <Nav />
      <main className="max-w-2xl mx-auto px-4 py-16">
        <h1 className="text-3xl font-extrabold text-white mb-8">Terms of Service</h1>
        <div className="prose prose-invert prose-sm max-w-none space-y-4 text-gray-300 leading-relaxed">
          <p><strong>Last updated:</strong> May 2026</p>
          <p>
            By using ContractLens (&quot;the Service&quot;), you agree to these terms. If you do not agree, do not use the Service.
          </p>
          <h2 className="text-lg font-bold text-white mt-8 mb-3">1. Service Description</h2>
          <p>
            ContractLens provides AI-generated contract analysis for informational purposes only. The Service uses artificial intelligence to review contract text and generate summaries, risk assessments, and recommendations.
          </p>
          <h2 className="text-lg font-bold text-white mt-8 mb-3">2. Not Legal Advice</h2>
          <p>
            ContractLens is NOT a law firm and does NOT provide legal advice. The analysis generated by the Service is for informational purposes only. You should consult a qualified attorney before signing any contract. The AI can miss nuances, misinterpret clauses, or miss context that a human lawyer would catch.
          </p>
          <h2 className="text-lg font-bold text-white mt-8 mb-3">3. User Responsibilities</h2>
          <p>
            You are responsible for maintaining the confidentiality of your account credentials. You agree not to upload contracts that contain illegal content or violate third-party rights. You retain all ownership rights to the contracts you upload.
          </p>
          <h2 className="text-lg font-bold text-white mt-8 mb-3">4. Data Handling</h2>
          <p>
            Uploaded contract files are processed and deleted within 24 hours. Contract text is used solely for generating your analysis and is not stored permanently. We do not sell or share your contract data with third parties.
          </p>
          <h2 className="text-lg font-bold text-white mt-8 mb-3">5. Limitation of Liability</h2>
          <p>
            The Service is provided &quot;as is&quot; without warranties of any kind. ContractLens shall not be liable for any damages arising from the use of the Service, including decisions made based on AI-generated analysis.
          </p>
          <h2 className="text-lg font-bold text-white mt-8 mb-3">6. Contact</h2>
          <p>
            Questions about these terms? Contact us at <a href="mailto:support@contractlens.io" className="text-brand-500 hover:underline">support@contractlens.io</a>.
          </p>
        </div>
      </main>
    </>
  );
}
